code_producers/src/llvm_elements/mod.rs, compiler/src/intermediate_representation/branch_bucket.rs
Call the LLVM verifier on the module before writing the LLVM IR to the output file. Currently, it just prints the verification result to stdout but we could make it terminate the build if there are an errors in the generated LLVM.
=> Run LLVM verification

code_producers/src/llvm_elements/template.rs
The initial 0 parameter was missing from the GEP instruction for indexing the local variable array leading to type mismatches caught by the verifier.
=> [VAN-276] fix gep indexing for local variables

code_producers/src/llvm_elements/instructions.rs, compiler/src/circuit_design/circuit.rs, compiler/src/circuit_design/function.rs, compiler/src/intermediate_representation/call_bucket.rs
Circom functions may attempt to call functions that are yet to be defined due to ordering. This fixes that by first creating all declarations and then defines the body of each function.
=> Fix function definitions to allow calls to yet to be defined functions [VAN-271]

code_producers/src/llvm_elements/fr.rs, code_producers/src/llvm_elements/instructions.rs, compiler/src/intermediate_representation/compute_bucket.rs
Implement `OperatorType::ToAddress` transformation based on C code implementation which performs a cast from the finite field data type to the int data type. Thus, pointer/address computations uses int instead of finite field operations.
=> [VAN-278] Generate FF to int cast for addresses

code_producers/src/llvm_elements/mod.rs, compiler/src/intermediate_representation/branch_bucket.rs, compiler/src/intermediate_representation/ir_interface.rs, compiler/src/intermediate_representation/loop_bucket.rs, compiler/src/translating_traits/mod.rs
The construction of looping and branching statements had some cases where a block in the LLVM IR did not end with a terminator or had multiple terminators (i.e. return followed by jump).
=> [VAN-348] Fix LLVM IR verification errors

circom/src/compilation_user.rs, circuit_passes/src/bucket_interpreter/mod.rs, circuit_passes/src/passes/loop_unroll.rs, circuit_passes/src/passes/mod.rs, circuit_passes/src/passes/unknown_index_sanitization.rs, code_producers/src/llvm_elements/array_switch.rs, code_producers/src/llvm_elements/functions.rs, code_producers/src/llvm_elements/instructions.rs, code_producers/src/llvm_elements/mod.rs, code_producers/src/llvm_elements/template.rs, compiler-tests/arrays/unknown_index_load_store.circom, compiler/src/circuit_design/circuit.rs, compiler/src/intermediate_representation/load_bucket.rs, compiler/src/intermediate_representation/store_bucket.rs, compiler/src/intermediate_representation/translate.rs
This is done by adding some information to `StoreBucket` and `LoadBucket`. If this information (function name) is present, it changes the normal LLVM IR generation to generate a function call rather than a direct load/store.
(Note: I considered adding this as transformation from a `LoadBucket`/`StoreBucket` -> `CallBucket`, but there's no way to get a pointer argument for a function in circom, since the idea of a "pointer" doesn't exist in circom. So, you can't pass a pointer to a signal to another function this way, unless it's just in the LLVM IR generation.)
=> [VAN-417] Add load/store functions that perform bounds checks on unknown indices

Cargo.lock, compiler-tests/arrays/array8.circom, compiler-tests/controlflow/van348F.circom, compiler/Cargo.toml, compiler/src/intermediate_representation/call_bucket.rs, compiler/src/intermediate_representation/store_bucket.rs
I have handled storing the return value in the caller after a function call for both scalar and array returns. I did not change the return type to void for the array returns but that issue is non-breaking and distinct so I can address it later. I just wanted to get this PR started in the meantime.
=> [VAN-396][VAN-387] store return values in caller after a function call

circuit_passes/src/bucket_interpreter/env.rs, circuit_passes/src/passes/memory.rs, code_producers/src/llvm_elements/mod.rs
also add template vs. function to the "Running" debug line
=> move error printout to the end (after code dump)

circom/tests/controlflow/van544.circom, code_producers/src/llvm_elements/instructions.rs
Automatically convert int values to i1 (via "not equal to 0" comparison) so that br instructions only use i1 for the branch condition (which is what is causing the module to fail to verify).
=> Ensure br is only called with i1

circom/tests/subcmps/subcmps2.circom, circuit_passes/src/passes/deterministic_subcomponent_invocation.rs, compiler/src/intermediate_representation/store_bucket.rs
The issue was coming from the Final data when function outputs were being assigned to subcomponents. I added a minimized test case to the set of tests (subcmps2.circom) as well as a fix in the DeterministicSubCmpInvokePass.
=> [VAN-543] unknown input status

circom/tests/type_conversions/bool_1.circom, circom/tests/type_conversions/bool_2.circom, circom/tests/type_conversions/bool_3.circom, circom/tests/type_conversions/bool_4.circom, code_producers/src/llvm_elements/instructions.rs
The logic functions (`fr_logic_*`), the library functions (like constraints and assertions), and branch instructions require `i1` (i.e., boolean) arguments. So, when storing the results of logic operations to a regular variable (which is always a bigint, i.e. `i256`) or implicitly converting a regular variable into a boolean (e.g., `if (foo)`), a conversion needs to occur in the LLVM IR. I've implemented the following changes:
- When creating a call, store, or return with boolean arguments, automatically add a conversion to boolean if the provided argument is a non-boolean integer (by adding a computation of `val != 0`). 
- When creating a call, store, or return with an integer argument, automatically add a conversion to the non-boolean integer if the provided argument is a boolean  (by …
=> [VAN-503] Convert to/from i1 as needed

circom/tests/calls/call_with_array.circom, circom/tests/calls/call_with_array_and_scalar.circom, code_producers/src/llvm_elements/fr.rs, code_producers/src/llvm_elements/instructions.rs, compiler/src/intermediate_representation/call_bucket.rs
- The implementation of fr_copy_n was "todo", so I added the array copying logic for it.
- Also applied array copying for function arguments based on the argument type size available in call bucket
=> [VAN-611] Fill in fr_copy_n, also apply to arguments

circom/tests/subcmps/array_copy_constraints.circom, code_producers/src/llvm_elements/mod.rs, compiler/src/intermediate_representation/constraint_bucket.rs, compiler/src/intermediate_representation/store_bucket.rs
Generates constraints for each array element when `fr_copy_n` is used. For an array of N elements, this will create N calls to `__constraint_values`.
=> Add array constraint generation

program_structure/src/program_library/error_definition.rs
=> Allow dumb terminals to not have color

circom/tests/loops/inner_conditional_1.circom, circom/tests/loops/inner_conditional_11.circom, circom/tests/loops/inner_conditional_4.circom, circom/tests/subcmps/subcmps3.circom, circom/tests/subcmps/subcmps4.circom, circom/tests/zzz/unreachable_code_crash.circom, circuit_passes/src/bucket_interpreter/value.rs, circuit_passes/src/passes/checks.rs, circuit_passes/src/passes/conditional_flattening.rs, circuit_passes/src/passes/loop_unroll/body_extractor.rs, circuit_passes/src/passes/loop_unroll/extracted_location_updater.rs
also stabilize lit test output ordering for flattened function version
=> [VAN-798] correct missing "run" functions and subcmp arguments

circom/tests/zzz/VAN-833.circom, circuit_passes/src/passes/loop_unroll/body_extractor.rs, circuit_passes/src/passes/loop_unroll/extracted_location_updater.rs
The old approach would append the `insert_after` list at the tail of the existing `InstructionList` once all instructions were processed but that would cause an assertion failure in some cases and was actually not quite correct to do. The new approach inserts the current `insert_after` list immediately following each instruction as they are processed.
=> [VAN-833] Correct handling of insertions from extracted location updater

circom/src/compilation_user.rs
The LLVM passes can change IR in a way that makes wat/wasm generation crash if running both at the same time.
=> Run LLVM passes after wat/wasm

compiler/src/circuit_design/template.rs
This forces the identical function merging pass to retain all `build` and `run` function definitions but the ones that would have been removed (due to being identical to some other function) will instead be converted into a delegating function like the following:
```
define dso_local void @MixS_8_build({ [0 x i256]*, i32 }* %0) section ",MixS" {
tail call void @MixS_10_build({ [0 x i256]*, i32 }* %0)
ret void
}
```
=> [VAN-846] use External linkage kind on all template functions

circuit_passes/src/bucket_interpreter/env/standard_env.rs, circuit_passes/src/bucket_interpreter/error.rs, circuit_passes/src/bucket_interpreter/mod.rs, circuit_passes/src/bucket_interpreter/operations.rs, circuit_passes/src/passes/loop_unroll/loop_env_recorder.rs, circuit_passes/src/passes/unknown_index_sanitization.rs
1. Fix regression introduced when converting panics to meaningful error messages. There was one location where the panic was caught and ignored so a Result::Err should have also been ignored in that location but was not.
2. Move helper functions for creating error messages into the error.rs file instead of the module file for the interpreter.
=> Fix a regression and refactor some functions to a better location

Cargo.lock, code_producers/Cargo.toml
The Veridise fork of inkwell contained only a single function addition which we don't use any longer so migrating back to the upstream repo.
=> Update inkwell dependency to latest release from upstream

circom/tests/constraints/arr_cpy_store.circom, circom/tests/loops/inner_loops.circom, circom/tests/loops/inner_loops2.circom, circom/tests/loops/inner_loops3.circom, circom/tests/loops/inner_loops4.circom, circuit_passes/src/passes/loop_unroll/mod.rs
For a single iteration, it creates too much boilerplate
=> Do not extract loops with just 1 iteration to a new function
